# Generated by Django 3.2.5 on 2021-07-21 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='prod',
        ),
    ]
